# Test in linux and macos
os:
  - linux
  - osx

# gcc4.9 works only on trusty
# use the trusty beta on travis

# we might not need trusty for the latest bytedeco build

#sudo: required
#dist: trusty

cache:
  directories:
    - $HOME/.m2
    - node
    - node_modules

# this is a Java project
language: java

# This is needed to link against the correct gcc binaries
# we update gcc and thus pull on listc++6, as opencv is build against that
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-4.9
#      - g++-4.9
#      - libstdc++6
#      - libxvidcore4
#      - x264
#      - libav-tools

# test on jdk8
jdk:
  - oraclejdk8