version: '{build}'
os: Windows Server 2012

branches:
  only:
    - master
skip_tags: true

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  MAVEN_OPTS: -Xmx4g
  JAVA_OPTS: -Xmx4g

build_script:
  - ./mvnw --version
  - ./mvnw clean package --batch-mode -DskipTests

test_script:
  - ./mvnw clean install --batch-mode -P!generate-frontend
  
cache:
  - C:\Users\appveyor\.m2
  - node_modules
  - node
